---
title: "Project Eddie Temperature and CO2 Global Change"
author: "Bill Perry"
date: "6/10/2019"
---


# Project Eddie Example Module for Global Change   
### Bill Perry   
### 2019 - 06 - 10
<br>    
This is an example test repository for the Prject Eddie Global Temperature change modulue.

The datafor this module come from several sources cited below and a link to the cleaned data are provided here as well.   
       
## <b>Modern Temperature Data</b>         
### The source of this data is:      
http://www.earth-policy.org/index.php?/data_center/C23/  
   
### The raw cleaned data can be found at with the last 4 years added:
https://raw.githubusercontent.com/wlperry/Project_Eddie/master/finalized_data/modern_temp.csv     
    
     
### The data consists of:
year      
average annual temperature in degrees C

## <b>Modern CO2 Data</b>       
### The original modern CO2 data can be found at:     
http://www.esrl.noaa.gov/gmd/ccgg/trends/  


### The cleaned data can be found at:    
https://raw.githubusercontent.com/wlperry/Project_Eddie/master/finalized_data/modern_co2.csv      

### The data consists of     
year    
co2_ppm    
uncertainty    
     
        
## <b>The Historic Ice Vostock Ice Core Data</b>     
### The original data can be found at:    
TO BE FILLED IN    
     
### The cleaned data can be found at:
https://raw.githubusercontent.com/wlperry/Project_Eddie/master/finalized_data/ancient_temp_co2.csv    
     
     
### The data consists of:
depth_m   
years_1000   
temp_c    
gas_age_1000s
co2_ppm    





     



